# -*- coding: utf-8 -*-
"""BARTBana_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kg9J25xkKQgQjJ9G7sfoSW_DMS2k_gvn
"""

!pip install sacrebleu

!pip install  transformers datasets torch
# -U -q

!pip install evaluate

from huggingface_hub import login

# Thay token của bạn vào đây:
login("YOUR_HF_TOKEN_HERE", add_to_git_credential=True)

import pandas as pd
import numpy as np
import re
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    EarlyStoppingCallback
)
import evaluate
# Đường dẫn mô hình bạn muốn fine-tune (đã train MLM trên tiếng Tày)
MODEL_CKPT = "IAmSkyDra/BARTBana_v5"

# Tên dataset đã chia train/test trên Hugging Face
# DATASET_NAME = "FiveC/Bana-delete-original"

# Kích thước token tối đa mỗi câu
MAX_SOURCE_LENGTH = 128
MAX_TARGET_LENGTH = 128

# --------------------------------------------------------
# 2. Chuẩn bị dữ liệu
# --------------------------------------------------------

import re
from datasets import load_dataset

def clean_text(text):
    """
    Làm sạch câu bằng cách:
    - Loại bỏ ký tự đặc biệt, xuống dòng, tab.
    - Xóa khoảng trắng thừa.
    """
    if not isinstance(text, str):
        return None
    text = re.sub(r'\\n|\|\\|[\n\r\t]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Load dataset đã có sẵn train/test (dạng translation)
dataset = load_dataset(DATASET_NAME)

# Làm sạch nội dung từng câu trong field translation
def clean_translation(batch):
    batch["translation"]["bahnaric"] = clean_text(batch["translation"]["bahnaric"])
    batch["translation"]["vietnamese"] = clean_text(batch["translation"]["vietnamese"])
    return batch

dataset = dataset.map(clean_translation)

print(dataset)

train_dataset = dataset["train"]
test_dataset = dataset["val"]
print("\n--- Đang xáo trộn tập train... ---")
train_dataset = train_dataset.shuffle(seed=42)
print("--- Xáo trộn hoàn tất! ---")

test_dataset[0]

# --------------------------------------------------------
# 3. Load tokenizer và mô hình
# --------------------------------------------------------

print(f"Loading tokenizer & model from {MODEL_CKPT} ...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_CKPT)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_CKPT)

def preprocess_function(examples):
    inputs = [ex["bahnaric"] for ex in examples["translation"]]
    targets = [ex["vietnamese"] for ex in examples["translation"]]

    model_inputs = tokenizer(
        inputs,
        max_length=MAX_SOURCE_LENGTH,
        truncation=True,
        padding="max_length"
    )

    # Token hóa phần đích (target)
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            targets,
            max_length=MAX_TARGET_LENGTH,
            truncation=True,
            padding="max_length"
        )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

print("Tokenizing dataset ...")
train_dataset = train_dataset.map(preprocess_function, batched=True)
test_dataset  = test_dataset.map(preprocess_function, batched=True)

remove_columns = ["translation", "__index_level_0__"]
train_dataset = train_dataset.remove_columns([c for c in remove_columns if c in train_dataset.column_names])
test_dataset  = test_dataset.remove_columns([c for c in remove_columns if c in test_dataset.column_names])

print(train_dataset.column_names)

# --------------------------------------------------------
# 5. Định nghĩa hàm tính SacreBLEU
# --------------------------------------------------------
import evaluate
sacrebleu = evaluate.load("sacrebleu")

def postprocess_text(preds, labels):
    """
    - Loại bỏ token đặc biệt, strip(), ...
    - pred: list[str], label: list[str].
    """
    preds = [pred.strip() for pred in preds]
    labels = [lbl.strip() for lbl in labels]
    return preds, labels

def compute_metrics(eval_preds):
    """
    eval_preds = (predictions, labels)
    """
    preds, labels = eval_preds

    # Xử lý -100 --> pad_token_id
    preds = np.where(preds != -100, preds, tokenizer.pad_token_id)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)

    # Giải mã
    pred_str = tokenizer.batch_decode(preds, skip_special_tokens=True)
    label_str = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # Tiền xử lý để sacrebleu chính xác
    pred_str, label_str = postprocess_text(pred_str, label_str)

    # SacreBLEU yêu cầu references dưới dạng list of list
    # Mỗi sample: list[ reference1, reference2, ... ]
    # Ở đây chỉ 1 reference => [[ref1], [ref2], ...]
    references = [[l] for l in label_str]

    results = sacrebleu.compute(predictions=pred_str, references=references)
    return {"sacrebleu": results["score"]}  # "score" là BLEU của sacrebleu

# --------------------------------------------------------
# 6. Thiết lập tham số huấn luyện Seq2Seq
# --------------------------------------------------------

# Với A100 40GB, bạn có thể dùng batch size lớn hơn (32, 64).
# Ở đây, ta chọn 32 để an toàn. Tuỳ bạn tăng/giảm.
BATCH_SIZE = 16

training_args = Seq2SeqTrainingArguments(
    f"BartBanaFinal-delete-original",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=100,
    predict_with_generate=True,         # Để mô hình generate ra text trong eval
    load_best_model_at_end=True,       # Tự động load checkpoint tốt nhất
    metric_for_best_model="sacrebleu", # So sánh theo SacreBLEU
    greater_is_better=True,
    save_total_limit=3,                # Giữ 3 checkpoint
    fp16=True,                         # Mixed precision, tăng tốc trên A100
    push_to_hub=True,                # Nếu muốn push lên Hugging Face Hub
    hub_model_id="FiveC/BartBanaFinal-delete-original",
)

# --------------------------------------------------------
# 7. Khởi tạo Trainer
# --------------------------------------------------------
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)]
)

# --------------------------------------------------------
# 8. Bắt đầu huấn luyện
# --------------------------------------------------------
from accelerate import Accelerator
accelerator = Accelerator()

print("Starting Training ...")
trainer.train()

# --------------------------------------------------------
# 9. Đánh giá trên tập test
# --------------------------------------------------------

print("Evaluating on test set ...")
metrics = trainer.evaluate(test_dataset)
print("Test metrics:", metrics)
print(f"SacreBLEU: {metrics['eval_sacrebleu']:.2f}")

# --------------------------------------------------------
# 10. (Tuỳ chọn) Đẩy mô hình lên Hugging Face Hub
# --------------------------------------------------------
trainer.push_to_hub()

# tokenizer.push_to_hub(repo_id="BartTay_final")
# model.push_to_hub(repo_id="BartTay_final")

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import evaluate
from torch.utils.data import DataLoader
import torch
from tqdm import tqdm  # Import tqdm for progress bar

# Load model and tokenizer
model_name = "BartBanaFinal-delete-original"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# BLEU metric using `evaluate`
bleu = evaluate.load("sacrebleu")
meteor = evaluate.load("meteor")

# Ensure model is on the correct device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Function to collate batches for the DataLoader
def collate_fn(batch):
    input_ids = torch.tensor([item["input_ids"] for item in batch], dtype=torch.long)
    attention_mask = torch.tensor([item["attention_mask"] for item in batch], dtype=torch.long)
    labels = torch.tensor([item["labels"] for item in batch], dtype=torch.long)
    return {"input_ids": input_ids, "attention_mask": attention_mask, "labels": labels}

# Wrap test_dataset with a DataLoader
batch_size = 64
test_dataloader = DataLoader(test_dataset, batch_size=batch_size, collate_fn=collate_fn)

# Evaluation function with progress bar
def evaluate_bleu(model, tokenizer, dataloader):
    model.eval()
    predictions = []
    references = []

    # Add progress bar
    with tqdm(total=len(dataloader), desc="Evaluating", unit="batch") as pbar:
        for batch in dataloader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            with torch.no_grad():
                outputs = model.generate(input_ids=input_ids, attention_mask=attention_mask, max_length=MAX_TARGET_LENGTH)

            # Decode predictions and references
            decoded_preds = tokenizer.batch_decode(outputs, skip_special_tokens=True)
            decoded_refs = tokenizer.batch_decode(labels, skip_special_tokens=True)

            predictions.extend(decoded_preds)
            references.extend([[ref] for ref in decoded_refs])  # BLEU expects a list of lists for references

            # Update progress bar
            pbar.update(1)

    # Compute BLEU score
    bleu_score = bleu.compute(predictions=predictions, references=references)
     # 🔸 Compute METEOR
    meteor_score = meteor.compute(predictions=predictions, references=references)
    return bleu_score["score"], meteor_score["meteor"]

# Evaluate on test dataset
# Gọi hàm và nhận 2 giá trị riêng biệt
bleu_score, meteor_score = evaluate_bleu(model, tokenizer, test_dataloader)

# In ra kết quả
print(f"BLEU Score: {bleu_score:.2f}")
print(f"METEOR Score: {meteor_score:.4f}")