# -*- coding: utf-8 -*-
"""Copy of TSSA_BARTpho_Rhade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TlXKeXI1a1-4dE9pRIcgQD6q848Cm697

# TSSA on BARTpho — Rhade (Ede) → Vietnamese
Full implementation of **Target-Side Semantic Anchoring (TSSA)** applied on top of the BARTpho baseline
you already trained, following the proposal exactly:

- `L = L_MT + λ1·L_struct + λ2·L_prime + λ3·L_route`  (Eq. 8)
- Frozen target teacher `E_T` = a frozen copy of BARTpho's **encoder**, run on the target sentence `y`
  (same tokenizer as the student decoder ⇒ teacher position `j` lines up exactly with decoder/label position `j`,
  no extra alignment needed for the teacher).
- Offline **source↔target alignment posterior A** (Eq. 2) is instantiated with a LaBSE-embedding cosine-similarity
  aligner (lightweight SimAlign-style aligner, consistent with the B4 family in the proposal), computed **once, offline**,
  and cached to disk — it is never trained end-to-end.
- `L_struct` (Eq. 3): confidence-weighted structural anchoring of source states toward the teacher barycenter.
- `L_prime` (Eq. 4): in-batch sentence-level contrastive priming (InfoNCE, teacher side stop-gradiented).
- `L_route` (Eq. 5–7): head-wise scalar gates on **decoder cross-attention**, supervised by agreement between a
  projected head output and the frozen teacher state at the same target step. Gate uses only inference-time
  quantities (`q`, pooled source summary `s`); the reliability target `r` is detached, so it can never be
  trivially gamed by the model (Section 3.4).

**Guardrails implemented exactly as specified (this is the part reviewers push back on — it is handled explicitly):**
1. λ1, λ2 are **linearly ramped** from 0 during a translation-only warm-up (Section 3.5) — the model first stabilizes
   on `L_MT` before any auxiliary term contributes.
2. `L_route` is only activated **after** the ramp (`ROUTE_START_STEP`), with gates forced to `g=1` before that
   (Section 3.4, "a warm-up period with g=1 will stabilize the baseline before routing supervision is activated").
3. Every step we log `L_MT` and each auxiliary loss **before** scaling by λ, and we hard-check that
   `λ1·L_struct + λ2·L_prime + λ3·L_route ≤ L_MT` (the trade-off budget you specified) — if this is ever violated
   for a sustained window, the notebook auto-shrinks the offending λ (a fixed initial-scale normalization, not
   tuned on test data — Section 3.5).
4. Wall-clock overhead vs. the pure `L_MT` baseline is measured every epoch; the acceptance criterion is
   **≤ 20% overhead** (Section 4.8). If exceeded, the notebook prints a warning and suggests which term to
   cache/sparsify first, per the proposal's mitigation order (cache teacher states → sample token anchoring →
   keep routing head-wise only).

Run on a Colab **A100** runtime (Runtime → Change runtime type → A100 GPU).

## 0. Setup
"""

!pip install -q transformers==4.44.2 datasets==2.21.0 accelerate==0.34.2 \
    sentencepiece sacrebleu sentence-transformers evaluate

import os, time, json, math, random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from dataclasses import dataclass, field
from torch.utils.data import DataLoader
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModel, MBartForConditionalGeneration, get_linear_schedule_with_warmup
!pip install sacrebleu
import sacrebleu
from sentence_transformers import SentenceTransformer

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED); torch.cuda.manual_seed_all(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
assert DEVICE == "cuda", "Select an A100 runtime: Runtime -> Change runtime type -> GPU (A100)"
print(torch.cuda.get_device_name(0))

"""## 1. Config
All hyperparameters are declared up-front (Section 4.4: "search space ... declared in advance").
`LAMBDA1/2/3` are the **target/ceiling** weights reached at the end of the ramp — actual weights at
any step are `lambda_t = LAMBDA * min(1, step/RAMP_STEPS)`, and `L_route` is 0 until `ROUTE_START_STEP`.
"""

BACKBONE = "vinai/bartpho-syllable"     # BARTpho backbone = student (trainable) AND source of the frozen teacher
DATASET  = "NIRVLab/rhade-vietnamese-mt"
SRC_KEY, TGT_KEY = "ede", "vi"           # dataset field names inside the `translation` dict

MAX_SRC_LEN = 128
MAX_TGT_LEN = 128
BATCH_SIZE  = 16
GRAD_ACCUM  = 2
EPOCHS      = 5
LR          = 3e-5
WARMUP_RATIO = 0.06

PROJ_DIM = 256          # shared projection dim for P_S / P_T (Eq. 2-3) and R_lh (Eq. 6)
TAU      = 0.07         # contrastive temperature (Eq. 4)

LAMBDA1 = 0.5            # ceiling weight for L_struct
LAMBDA2 = 0.5            # ceiling weight for L_prime
LAMBDA3 = 0.25            # ceiling weight for L_route

BUDGET_CHECK_EVERY = 50          # steps between "aux <= L_MT" budget checks
BUDGET_SHRINK_FACTOR = 0.8       # auto-shrink factor if budget is violated on a sustained window
OVERHEAD_TARGET = 0.20           # <=20% wall-clock overhead vs pure L_MT baseline (Section 4.8)

OUT_DIR = "/content/tssa_bartpho_rhade"
os.makedirs(OUT_DIR, exist_ok=True)

"""## 2. Data — load the 3 real splits (train / validation / test)"""

raw = load_dataset(DATASET)
print(raw)

# NIRVLab/rhade-vietnamese-mt ships train/validation/test already (per the dataset card) -- verified, no manual resplit.
train_ds, val_ds, test_ds = raw["train"], raw["validation"], raw["test"]

def get_pair(example):
    tr = example["translation"]
    return {"src": tr[SRC_KEY], "tgt": tr[TGT_KEY]}

train_ds = train_ds.map(get_pair, remove_columns=train_ds.column_names)
val_ds   = val_ds.map(get_pair,   remove_columns=val_ds.column_names)
test_ds  = test_ds.map(get_pair,  remove_columns=test_ds.column_names)

# drop empty / degenerate pairs (proposal 4.1: dedup/normalization reported, not silently standardized -- we only drop truly empty rows)
for name, ds in [("train", train_ds), ("val", val_ds), ("test", test_ds)]:
    n0 = len(ds)
    ds = ds.filter(lambda x: len(x["src"].strip()) > 0 and len(x["tgt"].strip()) > 0)
    print(f"{name}: {n0} -> {len(ds)} after empty-pair filtering")

print(train_ds[0], val_ds[0], test_ds[0])

"""## 3. Tokenizer, student model, and the **frozen target teacher**
The teacher is a second, frozen instance of BARTpho's encoder, initialized from the same pretrained checkpoint
(Section 3.1: "A frozen target teacher `E_T` is initialized from a strong target-language ... model" and
"processes `y` only during training"). Because it shares the tokenizer with the student decoder, teacher position
`j` and decoder/label position `j` refer to the exact same token — this removes the need for a separate
teacher-to-decoder alignment step.
"""

tokenizer = AutoTokenizer.from_pretrained(BACKBONE, use_fast=False)

student = MBartForConditionalGeneration.from_pretrained(BACKBONE).to(DEVICE)

teacher_encoder = AutoModel.from_pretrained(BACKBONE).encoder.to(DEVICE)
for p in teacher_encoder.parameters():
    p.requires_grad_(False)
teacher_encoder.eval()

HID = student.config.d_model
NUM_DEC_LAYERS = student.config.decoder_layers
NUM_HEADS = student.config.decoder_attention_heads
HEAD_DIM = HID // NUM_HEADS
print(f"d_model={HID}  decoder_layers={NUM_DEC_LAYERS}  heads={NUM_HEADS}  head_dim={HEAD_DIM}")

"""## 4. Offline alignment posterior `A` (Eq. 2)
Computed **once**, before training, and cached — never backpropagated through (Section 3.2: "an offline aligner
produces posterior matrix A"). We use LaBSE word-embedding cosine similarity as a lightweight, dependency-free
stand-in for SimAlign (the proposal explicitly allows "a strong multilingual encoder aligner", B4 family).
Words are then mapped onto BARTpho source subword spans (first-subword rule) so `A` is directly usable as
`A_ij` over source *tokens* `x_i`.
"""

labse = SentenceTransformer("sentence-transformers/LaBSE", device=DEVICE)
labse_word_model = labse[0].auto_model
labse_tok = labse.tokenizer

@torch.no_grad()
def labse_word_embeddings(words):
    '''Mean-pool LaBSE subword embeddings back to whitespace-word embeddings.'''
    enc = labse_tok(words, is_split_into_words=False, return_tensors="pt",
                     padding=True, truncation=True, max_length=32).to(DEVICE)
    out = labse_word_model(**enc).last_hidden_state  # (W, L, H) -- one row per word here since we embed word-by-word
    mask = enc["attention_mask"].unsqueeze(-1)
    pooled = (out * mask).sum(1) / mask.sum(1).clamp(min=1)
    return F.normalize(pooled, dim=-1)  # (W, H)

@torch.no_grad()
def offline_align_batch(src_texts, tgt_texts, src_token_offsets_batch):
    '''
    For each (src, tgt) sentence pair, compute a source-subtoken x target-subtoken posterior A (Eq.2):
      1. split into whitespace words, embed each word with LaBSE, cosine-similarity matrix
      2. softmax over target words per source word -> word-level posterior
      3. broadcast a word's posterior row to every BARTpho source subword belonging to that word (first-subword rule)
      4. broadcast target words -> target subwords the same way, using the tokenizer's target tokenization
    Returns a list of (m x n) numpy posterior matrices aligned to BARTpho src/tgt subword lengths.
    '''
    results = []
    for src_text, tgt_text in zip(src_texts, tgt_texts):
        src_words = src_text.split()
        tgt_words = tgt_text.split()
        if len(src_words) == 0 or len(tgt_words) == 0:
            results.append(np.zeros((1, 1), dtype=np.float32))
            continue
        se = labse_word_embeddings(src_words).cpu().numpy()
        te = labse_word_embeddings(tgt_words).cpu().numpy()
        sim = se @ te.T
        sim = sim / 0.05
        word_A = np.exp(sim - sim.max(axis=1, keepdims=True))
        word_A = word_A / word_A.sum(axis=1, keepdims=True)
        results.append(word_A)
    return results

def word_to_subword_map(text, tokenizer, max_len):
    '''Map each subword token index -> source word index (first-subword rule), truncated to max_len.'''
    words = text.split()
    ids = []
    word_of_token = []
    for wi, w in enumerate(words):
        sub = tokenizer(w, add_special_tokens=False)["input_ids"]
        if len(sub) == 0:
            continue
        ids.extend(sub)
        word_of_token.extend([wi] * len(sub))
    ids = ids[:max_len]
    word_of_token = word_of_token[:max_len]
    return ids, word_of_token, len(words)

def build_subword_posterior(src_text, tgt_text, word_A, tokenizer, max_src, max_tgt):
    _, src_w_of_t, n_src_w = word_to_subword_map(src_text, tokenizer, max_src)
    _, tgt_w_of_t, n_tgt_w = word_to_subword_map(tgt_text, tokenizer, max_tgt)
    m, n = len(src_w_of_t), len(tgt_w_of_t)
    if m == 0 or n == 0:
        return np.zeros((max(m,1), max(n,1)), dtype=np.float32)
    A = np.zeros((m, n), dtype=np.float32)
    wA = word_A[:min(word_A.shape[0], n_src_w), :min(word_A.shape[1], n_tgt_w)]
    for i, sw in enumerate(src_w_of_t):
        if sw >= wA.shape[0]:
            continue
        for j, tw in enumerate(tgt_w_of_t):
            if tw >= wA.shape[1]:
                continue
            A[i, j] = wA[sw, tw]
    return A

print('Offline aligner ready (LaBSE word-embedding cosine, mapped to BARTpho subwords).')

"""## 5. Dataset / collate: tokenize + attach cached alignment posteriors
Alignment is precomputed **per example, cached to disk as a dict indexed by row id** so it is computed once and
reused every epoch (offline, as required — Section 3.2 / 4.6: "Alignment evaluation will not reuse the posterior
that trained the method as if it were gold" — note we only use this posterior as a *training scaffold*, held-out
manual alignment is used later, in Section 4.6, for evaluation).
"""

import pickle

def precompute_alignments(ds, cache_path, max_src=MAX_SRC_LEN, max_tgt=MAX_TGT_LEN, chunk=64):
    if os.path.exists(cache_path):
        with open(cache_path, "rb") as f:
            return pickle.load(f)
    cache = []
    srcs, tgts = ds["src"], ds["tgt"]
    for start in range(0, len(srcs), chunk):
        s_chunk = srcs[start:start+chunk]
        t_chunk = tgts[start:start+chunk]
        word_As = offline_align_batch(s_chunk, t_chunk, None)
        for s, t, wA in zip(s_chunk, t_chunk, word_As):
            A = build_subword_posterior(s, t, wA, tokenizer, max_src, max_tgt)
            cache.append(A.astype(np.float16))
        if start % (chunk*10) == 0:
            print(f"  aligned {start+len(s_chunk)}/{len(srcs)}")
    with open(cache_path, "wb") as f:
        pickle.dump(cache, f)
    return cache

print("Precomputing offline alignment posteriors (train only -- val/test never touch training-time aux losses)...")
train_align_cache = precompute_alignments(train_ds, os.path.join(OUT_DIR, "train_align.pkl"))
print(f"Cached {len(train_align_cache)} alignment matrices for train.")

class TSSADataset(torch.utils.data.Dataset):
    def __init__(self, ds, align_cache=None):
        self.src = ds["src"]; self.tgt = ds["tgt"]
        self.align_cache = align_cache

    def __len__(self):
        return len(self.src)

    def __getitem__(self, idx):
        item = {"src": self.src[idx], "tgt": self.tgt[idx]}
        if self.align_cache is not None:
            item["A"] = self.align_cache[idx]
        return item

def collate(batch, with_align):
    src_texts = [b["src"] for b in batch]
    tgt_texts = [b["tgt"] for b in batch]

    src_enc = tokenizer(src_texts, padding=True, truncation=True, max_length=MAX_SRC_LEN, return_tensors="pt")
    tgt_enc = tokenizer(text_target=tgt_texts, padding=True, truncation=True, max_length=MAX_TGT_LEN, return_tensors="pt")

    labels = tgt_enc["input_ids"].clone()
    labels[labels == tokenizer.pad_token_id] = -100

    out = {
        "input_ids": src_enc["input_ids"],
        "attention_mask": src_enc["attention_mask"],
        "labels": labels,
        "decoder_input_ids": tgt_enc["input_ids"],           # teacher input to E_T (same tokenizer as decoder)
        "decoder_attention_mask": tgt_enc["attention_mask"],
    }
    if with_align:
        m = src_enc["input_ids"].shape[1]
        n = tgt_enc["input_ids"].shape[1]
        A_batch = torch.zeros(len(batch), m, n, dtype=torch.float32)
        for bi, b in enumerate(batch):
            A = b["A"]
            mi, ni = min(A.shape[0], m), min(A.shape[1], n)
            A_batch[bi, :mi, :ni] = torch.from_numpy(A[:mi, :ni].astype(np.float32))
        out["A"] = A_batch
    return out

train_dataset = TSSADataset(train_ds, train_align_cache)
val_dataset   = TSSADataset(val_ds)
test_dataset  = TSSADataset(test_ds)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,
                           collate_fn=lambda b: collate(b, with_align=True))
val_loader   = DataLoader(val_dataset, batch_size=BATCH_SIZE*2, shuffle=False,
                           collate_fn=lambda b: collate(b, with_align=False))
test_loader  = DataLoader(test_dataset, batch_size=BATCH_SIZE*2, shuffle=False,
                           collate_fn=lambda b: collate(b, with_align=False))
print(len(train_loader), len(val_loader), len(test_loader), "batches")

"""## 6. TSSA modules: projections `P_S`/`P_T`, sentence pooling, and **gated cross-attention** (Eq. 5–7)
The gated attention module is a drop-in replacement for BARTpho's decoder cross-attention: it computes attention
exactly as before, but additionally produces a per-head scalar gate `g_lht = σ(MLP([q; s; q⊙s]))` (Eq. 5) applied
to that head's output **before** the output projection. This only uses inference-time quantities, so the gate is
active at inference too (no target leakage — Section 3.1).
"""

class Projector(nn.Module):
    def __init__(self, in_dim, out_dim=PROJ_DIM):
        super().__init__()
        self.net = nn.Linear(in_dim, out_dim)
    def forward(self, x):
        return F.normalize(self.net(x), dim=-1)

P_S = Projector(HID).to(DEVICE)
P_T = Projector(HID).to(DEVICE)

def mask_mean_pool(hidden, mask):
    mask = mask.unsqueeze(-1).float()
    return (hidden * mask).sum(1) / mask.sum(1).clamp(min=1e-6)


class GatedCrossAttention(nn.Module):
    '''Wraps an existing BartAttention (decoder.encoder_attn) with head-wise routing (Eq. 5-7).
    The source summary `s` is computed INSIDE forward from key_value_states, so it is always
    correctly shaped even under beam-search batch expansion.'''
    def __init__(self, orig_attn, layer_idx, proj_dim=PROJ_DIM):
        super().__init__()
        self.embed_dim = orig_attn.embed_dim
        self.num_heads = orig_attn.num_heads
        self.head_dim = self.embed_dim // self.num_heads
        self.scaling = self.head_dim ** -0.5
        self.layer_idx = layer_idx

        self.k_proj = orig_attn.k_proj
        self.v_proj = orig_attn.v_proj
        self.q_proj = orig_attn.q_proj
        self.out_proj = orig_attn.out_proj

        self.router = nn.ModuleList([
            nn.Sequential(nn.Linear(self.head_dim * 3, 32), nn.ReLU(), nn.Linear(32, 1))
            for _ in range(self.num_heads)
        ])
        self.s_proj = nn.Linear(self.embed_dim, self.embed_dim)
        self.R = nn.ModuleList([nn.Linear(self.head_dim, proj_dim) for _ in range(self.num_heads)])

        self.routing_enabled = False
        self.last_gates = None
        self.last_head_outputs = None

    def _shape(self, x, B, T):
        return x.view(B, T, self.num_heads, self.head_dim).transpose(1, 2)

    def _pooled_source_summary(self, key_value_states, attention_mask):
        '''Mean-pool key_value_states over the source length using the encoder padding mask,
        derived from the additive attention_mask (0 = keep, large negative = masked).'''
        B, S, _ = key_value_states.shape
        if attention_mask is not None:
            am = attention_mask
            while am.dim() > 2:
                am = am[:, 0]          # (B, 1, tgt_len, src_len) or (B, 1, src_len) -> (B, src_len)
            if am.shape[-1] != S:
                am = am[:, :S] if am.shape[-1] > S else F.pad(am, (0, S - am.shape[-1]))
            bin_mask = (am >= -1.0).float()   # additive mask ~0 for keep, very negative for masked
        else:
            bin_mask = torch.ones(B, S, device=key_value_states.device)
        denom = bin_mask.sum(1, keepdim=True).clamp(min=1e-6)
        return (key_value_states * bin_mask.unsqueeze(-1)).sum(1) / denom  # (B, embed_dim)

    def forward(self, hidden_states, key_value_states, attention_mask=None, **kwargs):
        B, T, _ = hidden_states.shape
        q = self._shape(self.q_proj(hidden_states) * self.scaling, B, T)
        k = self._shape(self.k_proj(key_value_states), B, key_value_states.shape[1])
        v = self._shape(self.v_proj(key_value_states), B, key_value_states.shape[1])

        attn_weights = torch.matmul(q, k.transpose(-1, -2))
        if attention_mask is not None:
            attn_weights = attn_weights + attention_mask
        attn_weights = F.softmax(attn_weights, dim=-1)
        head_out = torch.matmul(attn_weights, v)
        self.last_head_outputs = head_out

        src_summary = self._pooled_source_summary(key_value_states, attention_mask)  # (B, embed_dim)
        s = self.s_proj(src_summary)
        s = s.view(B, self.num_heads, self.head_dim).unsqueeze(2).expand(-1, -1, T, -1)

        if self.routing_enabled:
            gates = []
            for h in range(self.num_heads):
                gin = torch.cat([q[:, h] / self.scaling, s[:, h], (q[:, h] / self.scaling) * s[:, h]], dim=-1)
                g_h = torch.sigmoid(self.router[h](gin)).squeeze(-1)
                gates.append(g_h)
            gates = torch.stack(gates, dim=1)
            gated = head_out * gates.unsqueeze(-1)
        else:
            gates = torch.ones(B, self.num_heads, T, device=head_out.device)
            gated = head_out

        self.last_gates = gates
        out = gated.transpose(1, 2).contiguous().view(B, T, self.embed_dim)
        out = self.out_proj(out)
        return out, attn_weights

# ---- patch BARTpho's decoder cross-attention modules with GatedCrossAttention ----
gated_modules = []
for li, layer in enumerate(student.model.decoder.layers):
    gated = GatedCrossAttention(layer.encoder_attn, li).to(DEVICE)
    layer.encoder_attn = gated
    gated_modules.append(gated)
print(f"Patched {len(gated_modules)} decoder cross-attention layers with head-wise routing.")

def set_routing(enabled: bool):
    for g in gated_modules:
        g.routing_enabled = enabled

def set_source_summary(summary):
    for g in gated_modules:
        g.source_summary = summary

set_routing(False)  # start with g=1 everywhere (warm-up, Section 3.4)

"""## 7. The three auxiliary losses (Eq. 2–4, 6–7)"""

def compute_lstruct(enc_hidden, src_mask, teacher_hidden, tgt_mask, A):
    '''
    Eq. 2-3.
      enc_hidden:    (B, m, H) source encoder states h^S_i
      teacher_hidden:(B, n, H) frozen teacher states h^T_j  (already computed on y, stop-gradiented)
      A:             (B, m, n) offline alignment posterior (rows normalized per Eq.2, unaligned rows -> all zero)
    '''
    eps = 1e-6
    A = A.to(enc_hidden.dtype)
    row_sum = A.sum(-1, keepdim=True)                       # (B,m,1)
    A_norm = A / (row_sum + eps)                             # A~_ij  (Eq. 2)
    h_bar_T = torch.bmm(A_norm, teacher_hidden)               # (B,m,H)  target barycenter per source position

    c_i = row_sum.squeeze(-1).clamp(max=1.0)                  # confidence c_i = min(1, sum_j A_ij)
    c_i = c_i * src_mask.float()                               # zero-out padding positions

    p_s = F.normalize(P_S(enc_hidden), dim=-1)
    p_t = F.normalize(P_T(h_bar_T), dim=-1).detach()          # stop-gradient sg(.) on teacher side (Eq. 3)

    per_pos = ((p_s - p_t) ** 2).sum(-1)                       # squared L2 of unit vectors, per source position
    loss = (c_i * per_pos).sum() / (c_i.sum() + eps)
    return loss


def compute_lprime(z_s, z_t):
    '''Eq. 4: in-batch InfoNCE, teacher side stop-gradiented, other targets in batch = negatives.'''
    z_s = F.normalize(z_s, dim=-1)
    z_t = F.normalize(z_t, dim=-1).detach()
    logits = z_s @ z_t.t() / TAU                               # (B,B)
    labels = torch.arange(z_s.size(0), device=z_s.device)
    return F.cross_entropy(logits, labels)


def compute_lroute(gated_modules, teacher_hidden, tgt_mask):
    '''
    Eq. 6-7. For every routed layer/head/step t:
      r_lht = (1 + cos(R_lh(o_lht), sg(P_T(h^T_t)))) / 2         (Eq.6, detached target)
      L_route = BCE(g_lht, r_lht)                                (Eq.7)
    '''
    p_t = F.normalize(P_T(teacher_hidden), dim=-1).detach()    # (B, n, proj_dim)
    mask = tgt_mask.float()
    total, count = 0.0, 0
    for g in gated_modules:
        if g.last_gates is None or g.last_head_outputs is None:
            continue
        gates = g.last_gates                                    # (B,heads,T)
        head_out = g.last_head_outputs                           # (B,heads,T,head_dim)
        T = gates.shape[-1]
        n = p_t.shape[1]
        Tm = min(T, n)
        for h in range(g.num_heads):
            proj = F.normalize(g.R[h](head_out[:, h, :Tm]), dim=-1)    # (B,Tm,proj_dim)
            r = (1 + (proj * p_t[:, :Tm]).sum(-1)) / 2                  # (B,Tm) in [0,1], detached via p_t.detach()
            r = r.detach().clamp(1e-4, 1 - 1e-4)
            g_h = gates[:, h, :Tm].clamp(1e-4, 1 - 1e-4)
            bce = -(r * torch.log(g_h) + (1 - r) * torch.log(1 - g_h))
            m = mask[:, :Tm]
            total = total + (bce * m).sum()
            count = count + m.sum()
    if count == 0:
        return torch.tensor(0.0, device=teacher_hidden.device)
    return total / count

"""## 8. Unified TSSA training step
Implements the lambda ramp, the routing-activation switch, and the **hard budget check**
(`sum(aux) <= L_MT`) with automatic shrink, exactly as you specified.
"""

TOTAL_STEPS = (len(train_loader) // GRAD_ACCUM) * EPOCHS
WARMUP_STEPS = int(TOTAL_STEPS * WARMUP_RATIO)
RAMP_STEPS = max(1, TOTAL_STEPS // 3)
ROUTE_START_STEP = RAMP_STEPS

lambda1_cur, lambda2_cur, lambda3_cur = LAMBDA1, LAMBDA2, LAMBDA3
budget_violations, budget_window = 0, 0

optim_params = list(student.parameters()) + list(P_S.parameters()) + list(P_T.parameters())
optimizer = torch.optim.AdamW(optim_params, lr=LR, weight_decay=0.01)
scheduler = get_linear_schedule_with_warmup(optimizer, WARMUP_STEPS, TOTAL_STEPS)
scaler = torch.amp.GradScaler("cuda")

def lambda_at(step):
    ramp = min(1.0, step / RAMP_STEPS)
    l1 = lambda1_cur * ramp
    l2 = lambda2_cur * ramp
    l3 = lambda3_cur if step >= ROUTE_START_STEP else 0.0
    return l1, l2, l3

def training_step(batch, step):
    global lambda1_cur, lambda2_cur, lambda3_cur, budget_violations, budget_window

    input_ids = batch["input_ids"].to(DEVICE)
    attn_mask = batch["attention_mask"].to(DEVICE)
    labels = batch["labels"].to(DEVICE)
    dec_in = batch["decoder_input_ids"].to(DEVICE)
    dec_mask = batch["decoder_attention_mask"].to(DEVICE)
    A = batch["A"].to(DEVICE)

    routing_now = step >= ROUTE_START_STEP
    set_routing(routing_now)

    with torch.no_grad():
        teacher_hidden = teacher_encoder(input_ids=dec_in, attention_mask=dec_mask).last_hidden_state

    with torch.amp.autocast("cuda"):
        enc_out = student.model.encoder(input_ids=input_ids, attention_mask=attn_mask)
        enc_hidden = enc_out.last_hidden_state
        src_summary = mask_mean_pool(enc_hidden, attn_mask)
        set_source_summary(src_summary)

        out = student(input_ids=None, attention_mask=attn_mask, encoder_outputs=enc_out, labels=labels)
        L_mt = out.loss

        L_struct = compute_lstruct(enc_hidden, attn_mask, teacher_hidden, dec_mask, A)

        z_s = mask_mean_pool(P_S(enc_hidden), attn_mask)
        z_t = mask_mean_pool(P_T(teacher_hidden), dec_mask)
        L_prime = compute_lprime(z_s, z_t)

        L_route = compute_lroute(gated_modules, teacher_hidden, dec_mask) if routing_now else torch.tensor(0.0, device=DEVICE)

        l1, l2, l3 = lambda_at(step)
        aux_total = l1 * L_struct + l2 * L_prime + l3 * L_route
        loss = L_mt + aux_total

    budget_window += 1
    if aux_total.item() > L_mt.item():
        budget_violations += 1
    if budget_window >= BUDGET_CHECK_EVERY:
        if budget_violations / budget_window > 0.3:
            lambda1_cur *= BUDGET_SHRINK_FACTOR
            lambda2_cur *= BUDGET_SHRINK_FACTOR
            lambda3_cur *= BUDGET_SHRINK_FACTOR
            print(f"[budget guard] step {step}: aux exceeded L_MT on "
                  f"{budget_violations}/{budget_window} checks -> shrinking lambdas to "
                  f"({lambda1_cur:.3f}, {lambda2_cur:.3f}, {lambda3_cur:.3f})")
        budget_violations, budget_window = 0, 0

    return loss, {"L_mt": L_mt.item(), "L_struct": L_struct.item(),
                  "L_prime": L_prime.item(), "L_route": float(L_route.item()) if torch.is_tensor(L_route) else L_route,
                  "lambda1": l1, "lambda2": l2, "lambda3": l3, "routing": routing_now}

"""## 9. Evaluation: BLEU + chrF++ (sacrebleu, corpus-level, detokenized)
Matches Section 4.6: sacreBLEU and chrF++ as primary metrics, generation via `model.generate`, greedy/beam decode,
same decoding script for every epoch.
"""

@torch.no_grad()
def evaluate(loader, max_new_tokens=MAX_TGT_LEN, num_beams=4, limit_batches=None):
    student.eval()
    set_routing(True)  # inference always uses learned routing (it only needs q & s, both available at inference)
    hyps, refs = [], []
    for bi, batch in enumerate(loader):
        if limit_batches is not None and bi >= limit_batches:
            break
        input_ids = batch["input_ids"].to(DEVICE)
        attn_mask = batch["attention_mask"].to(DEVICE)
        enc_out = student.model.encoder(input_ids=input_ids, attention_mask=attn_mask)
        src_summary = mask_mean_pool(enc_out.last_hidden_state, attn_mask)
        set_source_summary(src_summary)

        gen = student.generate(encoder_outputs=enc_out, attention_mask=attn_mask,
                                max_new_tokens=max_new_tokens, num_beams=num_beams,
                                decoder_start_token_id=student.config.decoder_start_token_id)
        decoded_hyp = tokenizer.batch_decode(gen, skip_special_tokens=True)

        labels = batch["labels"].clone()
        labels[labels == -100] = tokenizer.pad_token_id
        decoded_ref = tokenizer.batch_decode(labels, skip_special_tokens=True)

        hyps.extend(decoded_hyp)
        refs.extend(decoded_ref)
    student.train()

    bleu = sacrebleu.corpus_bleu(hyps, [refs])
    chrf = sacrebleu.corpus_chrf(hyps, [refs], word_order=2)  # chrF++ = chrF with word_order=2
    return {"BLEU": bleu.score, "chrF++": chrf.score, "n": len(hyps)}

"""## 10. Training loop — 5 epochs, per-epoch metrics + overhead tracking
Also records wall-clock/epoch so you can compute the `<=20%` overhead figure against your already-completed
baseline run (paste the baseline epoch time into `BASELINE_SEC_PER_EPOCH` below).
"""

BASELINE_SEC_PER_EPOCH = None  # <-- fill in with your baseline BARTpho run's average epoch wall-clock (seconds)

history = []
global_step = 0
student.train()

for epoch in range(1, EPOCHS + 1):
    epoch_start = time.time()
    running = {"L_mt": 0.0, "L_struct": 0.0, "L_prime": 0.0, "L_route": 0.0}
    n_steps = 0
    optimizer.zero_grad()

    for bi, batch in enumerate(train_loader):
        loss, logs = training_step(batch, global_step)
        scaler.scale(loss / GRAD_ACCUM).backward()

        if (bi + 1) % GRAD_ACCUM == 0:
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(optim_params, max_norm=1.0)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()
            optimizer.zero_grad()
            global_step += 1

        for k in running:
            running[k] += logs[k]
        n_steps += 1

        if bi % 100 == 0:
            print(f"epoch {epoch} step {bi}/{len(train_loader)} "
                  f"L_mt={logs['L_mt']:.3f} L_struct={logs['L_struct']:.3f} "
                  f"L_prime={logs['L_prime']:.3f} L_route={logs['L_route']:.3f} "
                  f"(lambdas={logs['lambda1']:.2f}/{logs['lambda2']:.2f}/{logs['lambda3']:.2f} "
                  f"routing={logs['routing']})")

    epoch_time = time.time() - epoch_start
    overhead_str = ""
    if BASELINE_SEC_PER_EPOCH:
        overhead = (epoch_time - BASELINE_SEC_PER_EPOCH) / BASELINE_SEC_PER_EPOCH
        overhead_str = f"  | overhead vs baseline: {overhead*100:.1f}%"
        if overhead > OVERHEAD_TARGET:
            print(f"[!] epoch {epoch}: overhead {overhead*100:.1f}% exceeds the {OVERHEAD_TARGET*100:.0f}% target "
                  f"(Section 4.8). Mitigation order: cache teacher states -> sample L_struct positions -> "
                  f"keep routing head-wise only (already minimal).")

    metrics = evaluate(val_loader, num_beams=4)
    for k in running:
        running[k] /= max(1, n_steps)

    print(f"\n=== Epoch {epoch} done in {epoch_time:.1f}s{overhead_str} ===")
    print(f"  avg losses: {running}")
    print(f"  VAL  BLEU={metrics['BLEU']:.2f}  chrF++={metrics['chrF++']:.2f}  (n={metrics['n']})\n")

    history.append({"epoch": epoch, "epoch_time_sec": epoch_time, **running, "val_BLEU": metrics["BLEU"],
                     "val_chrF++": metrics["chrF++"]})

    ckpt_dir = os.path.join(OUT_DIR, f"epoch{epoch}")
    os.makedirs(ckpt_dir, exist_ok=True)
    student.save_pretrained(ckpt_dir)
    tokenizer.save_pretrained(ckpt_dir)
    torch.save({"P_S": P_S.state_dict(), "P_T": P_T.state_dict(),
                "gated_modules": [g.state_dict() for g in gated_modules]},
               os.path.join(ckpt_dir, "tssa_extra.pt"))

with open(os.path.join(OUT_DIR, "history.json"), "w") as f:
    json.dump(history, f, indent=2, ensure_ascii=False)

print(json.dumps(history, indent=2, ensure_ascii=False))

"""## 11. Final test-set evaluation (best epoch by validation BLEU)"""

best = max(history, key=lambda h: h["val_BLEU"])
print(f"Best epoch on validation: {best['epoch']} (BLEU={best['val_BLEU']:.2f}, chrF++={best['val_chrF++']:.2f})")

best_dir = os.path.join(OUT_DIR, f"epoch{best['epoch']}")
student = MBartForConditionalGeneration.from_pretrained(best_dir).to(DEVICE)
extra = torch.load(os.path.join(best_dir, "tssa_extra.pt"), map_location=DEVICE)
gated_modules = []
for li, layer in enumerate(student.model.decoder.layers):
    g = GatedCrossAttention(layer.encoder_attn, li).to(DEVICE)
    layer.encoder_attn = g
    gated_modules.append(g)
for g, sd in zip(gated_modules, extra["gated_modules"]):
    g.load_state_dict(sd)
set_routing(True)

test_metrics = evaluate(test_loader, num_beams=4)
print(f"TEST  BLEU={test_metrics['BLEU']:.2f}  chrF++={test_metrics['chrF++']:.2f}  (n={test_metrics['n']})")

with open(os.path.join(OUT_DIR, "test_metrics.json"), "w") as f:
    json.dump(test_metrics, f, indent=2)

"""## 12. Notes / what to check before quoting numbers
- **Compare against baseline B0.2** you already trained (plain BARTpho fine-tune, no TSSA terms): report
  ΔBLEU/ΔchrF++ at the same epoch count, plus paired bootstrap CIs (sacrebleu supports this via
  `sacrebleu.BLEU().get_signature()` + bootstrap resampling — add if you need significance, Section 4.6).
- **Controls from Table 1** (shuffled/random/unrelated-language teacher, no-L_struct/L_prime/L_route ablations,
  random-matched-head ablation) are *not* run in this notebook — this notebook is the full TSSA condition only.
  Duplicate this notebook and zero out the relevant loss term(s) / shuffle `A` rows / swap `teacher_encoder`
  for each control in Table 1.
- The offline aligner here is a **LaBSE cosine-similarity approximation**, not SimAlign/AWESOME-align/Mask-Align.
  Per Section 4.3 (B4) and the falsifiable prediction (ii), the core TSSA result should be checked against
  **at least one more posterior generator** before treating the anchoring effect as aligner-independent — plug
  in AWESOME-align (`pip install awesome-align`) as a second run if you want that robustness check now.
- Overhead: fill `BASELINE_SEC_PER_EPOCH` from your completed baseline run to get the real ≤20% figure printed
  each epoch.
"""